resolver: nightly-2015-10-27

packages:
- '.'
- location:
    git: git@github.com:snapframework/snap-core.git
    commit: b5ca1f086f8cd49a8f139e2547d597a87ddc3ef1
  extra-dep: true
- location:
    git: git@github.com:snapframework/snap-server.git
    commit: d84500c262b9125e5f673e1db517ce54ae5fab93
  extra-dep: true
- location:
    git: git@github.com:snapframework/io-streams-haproxy.git
    commit: ab208d49fe73c9cf05e46c0d929eec311fb0cfd9
  extra-dep: true
- location:
    git: git@github.com:snapframework/snap.git
    commit: da847284b0da2abb66051c6e1084f5f9e0c720f0
  extra-dep: true
- location:
    git: git@github.com:snapframework/heist.git
    commit: 2743031c4d92ba08cf4e3e3cf960807b5158c6f3
  extra-dep: true

extra-deps:
- readable-0.3.1
